### ISSUE TITLE
[heads up] Nextclade v2.0

### ISSUE THREAD

**Issue by fanninpm** [UPHL-BioNGS/Cecret#101]
Today, [Nextclade v2.0 was released](https://github.com/nextstrain/nextclade/releases/tag/2.0.0), with a lot of improvements (especially in performance). However, the new version contains a couple of breaking changes that may break your workflow…

- The input FASTA argument is now a positional argument, and it's now possible to specify more than one input FASTA file (no more need to `cat` them together!).
- The `--output-dir` flag has now been superseded by the `--output-all` flag. (Also, the `--output-{json,csv,tsv,tree}` flags have become redundant if you only use the default names for those output files. [Here is the file that specifies the CLI flags and the default output file names.](https://github.com/nextstrain/nextclade/blob/2.0.0/packages_rs/nextclade-cli/src/cli/nextclade_cli.rs))

Best of luck with the new version!

**Comment by erinyoung** [comment]
Thank you for letting me know! I had this in my calendar, but then didn't get to it. I'll hopefully have a new version and update by the end of the week this week.

**Comment by erinyoung** [comment]
Thank you again for this issue. I updated the nextclade and nextalign processes and it appears everything is working fine again.
