### ISSUE TITLE
nextclade error

### ISSUE THREAD

**Issue by tang27abu** [UPHL-BioNGS/Cecret#108]
There is an error when I run the cecret workflow using staphb-toolkit today.I run this command for many datasets before and it works fine. 
I saw this [issue](https://github.com/UPHL-BioNGS/Cecret/issues/101) for the nextcade update. However, when I check the errors, it seems like it still using the `--output-dir` instead of `--output-all`. I have upgrade the staphb-toolkit before I run the workflow but it doesn't work. I think it probably because staphb-toolkit doesn't update. I have checked latest release date for staphb-toolkit is April 25. 

Here is my command:
`staphb-wf cecret fastq_dir --output out --config cecret.config`

nextflow error:
```
Error executing process > 'nextclade (Clade Determination)'

Caused by:
  Process `nextclade (Clade Determination)` terminated with an error exit status (2)

Command executed:

  mkdir -p nextclade dataset logs/nextclade
  log_file=logs/nextclade/nextclade.5cb932f9-fc35-4591-84a7-5fafd637a83e.log
  err_file=logs/nextclade/nextclade.5cb932f9-fc35-4591-84a7-5fafd637a83e.err

  date | tee -a $log_file $err_file > /dev/null
  nextclade --version >> $log_file
  nextclade_version=$(nextclade --version)

  nextclade dataset get --name sars-cov-2 --output-dir dataset

  for fasta in 1.consensus.fa 2.consensus.fa 3.consensus.fa 4.consensus.fa 5.consensus.fa
  do
    cat $fasta >> ultimate_fasta.fasta
  done

  nextclade        --input-fasta=ultimate_fasta.fasta       --input-dataset dataset       --output-json=nextclade/nextclade.json       --output-csv=nextclade/nextclade.csv       --output-tsv=nextclade/nextclade.tsv       --output-tree=nextclade/nextclade.auspice.json       --output-dir=nextclade       --output-basename=nextclade       2>> $err_file >> $log_file
  cp ultimate_fasta.fasta nextclade/combined.fasta

Command exit status:
  2

Command output:
  (empty)

Work dir:
  /storage/hpc/group/cov-sur/datasets/data/fastq/work/44/e4b578e9b613d8ea3fc2973cae69e8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

```

**Comment by erinyoung** [comment]
I forgot about the StaPH-B toolkit version!!! I'll try to get around to patching Cecret in the staphB toolkit tomorrow.

**Comment by erinyoung** [comment]
I've created a PR for the staphB toolkit. You can check its progress here : https://github.com/StaPH-B/staphb_toolkit/pull/85/

**Comment by erinyoung** [comment]
@arodzh-sudo , I don't know if you heard, but the Staph-B toolkit has now updated.

The staphB toolkit 2.0.0 https://github.com/StaPH-B/staphb_toolkit/releases/tag/2.0.0 pulls Cecret from this repo, so it should now be up-to-date.
