### ISSUE TITLE
All N's in MPX consensus

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Cecret#109]
Our local MPX sequence had all N's in it's consensus sequence, whereas a comparative SRR sequence did not. So a complete SNP matrix was not produced, though bcftools_variants ran successfully for both.

I therefore uncommented 3 lines in cecret.config to make sure ivar_consensus was working, but had the same results.

Do I need to use ivar_variants instead of bcftools_variants?

**Comment by erinyoung** [comment]
What depth are you using? 10X is likely enough if not using amplicon libraries.

**Comment by DrB-S** [comment]
That explains it! It was set to 100.
Thanks!

**Comment by DrB-S** [comment]
That was the problem.
