### ISSUE TITLE
iqtree2 failure for monkeypox - wrong outgroup header in nextalign.aligned.fasta

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Cecret#110]
Running from UPHL-BioNGS/Cecret with the following execution error:

[24/8ac928] NOTE: Process `msa:iqtree2 (Creating phylogenetic tree with iqtree)` terminated with an error exit status (2) -- Execution is retried (1)
Error executing process > 'msa:iqtree2 (Creating phylogenetic tree with iqtree)'

Caused by:
  Process `msa:iqtree2 (Creating phylogenetic tree with iqtree)` terminated with an error exit status (2)

Command executed:

  mkdir -p iqtree2 logs/msa:iqtree2
  log_file=logs/msa:iqtree2/msa:iqtree2.7be2fac2-15c3-4970-aa30-aadd189177a2.log
  err_file=logs/msa:iqtree2/msa:iqtree2.7be2fac2-15c3-4970-aa30-aadd189177a2.err

  date | tee -a $log_file $err_file > /dev/null
  iqtree2 --version >> $log_file

  if [ -n "NC_063383.1" ] && [ "NC_063383.1" != "null" ] && [ "nextalign" != "nextclade" ]
  then
    outgroup="-o NC_063383.1"
    cat nextalign.aligned.fasta | sed 's/NC_063383.1.*/NC_063383.1/g' > nextalign.aligned.fasta.renamed
  else
    outgroup=""
    mv nextalign.aligned.fasta nextalign.aligned.fasta.renamed
  fi

  # creating a tree
  iqtree2 -ninit 2 -n 2 -me 0.05 -m GTR -o NC_063383.1       -nt AUTO       -ntmax 8       -s nextalign.aligned.fasta.renamed       -pre iqtree2/iqtree2       $outgroup       >> $log_file 2>> $err_file

Command exit status:
  2

Command output:
  (empty)

Work dir:
  /data/Sequence_analysis/Cecret/Analyses/monkeypox/iSeqs_Runs_220727/work/14/3f4bbbaca74412d37dbeb3cfe80aa3

==
The sequence header in nextalign.aligned.fasta was:
>ref_in_coord Reference sequence in coord.fasta coordinates

It should have been:
>NC_063383.1

So the sed command above didn't work:
sed 's/NC_063383.1.*/NC_063383.1/g'

**Comment by DrB-S** [comment]
I created a fastas directory and added NC_063383.1.fasta to the dir. 
This time Cecret completed successfully and iqtree2 created a tree, but NC_063383.1 was represented twice in both snp-dists.txt and iqtree2 as:
  NC_063383.1
and
  ref_in_coord

annotation:vadr (QC metrics) failed (as it has been doing) and I received the following warning:

WARN: Input tuple does not match input set cardinality declared by process `summary` -- offending value: [AZMPXV-0001, 11581, 185612, 0, 197193, Consensus_AZMPXV-0001.consensus_threshold_0.6_quality_20, fastp 0.23.2, minimap2 : 2.24-r1122, iVar version 1.3.1, 6401948, 3259911, 3259911, 0.21 0.21, 91.03, 64, 67, 0, 100, 18.3682, 179560, null, null]

**Comment by erinyoung** [comment]
I ran into this same issue. Stand by.

**Comment by DrB-S** [comment]
I think I found it in your documentation.
I cannot specify the outgroup in params.iqtree2_outgroup AND params.iqtree2_options in the config file.
I commented out the first mention and am testing:
//params.iqtree2_outgroup = 'NC_063383.1'
params.iqtree2_options = '-ninit 2 -n 2 -me 0.05 -m GTR -o NC_063383.1'

**Comment by erinyoung** [comment]
Yeah. That'll fail things. I separated the two variables so that it was easier to specify the outgroup.
