### ISSUE TITLE
How to output iqtree results into specific directory?

### ISSUE THREAD

**Issue by ybdong919** [UPHL-BioNGS/Cecret#124]

**Comment by erinyoung** [comment]
The directory of results for iqtree2 are set by the `outdir` parameter. Specifically, `${params.outdir}/iqtree2`. 

The default outdir value is `cecret` in your current directory, but you can change this by running
```
nextflow run UPHL-BioNGS/Cecret --reads <path to reads> --outdir <path to where you want your results>
```

Or by setting the parameter value in a config file:
```
params.outdir = '<path to where you want your results>'
```
