### ISSUE TITLE
ONT

### ISSUE THREAD

**Issue by erinyoung** [UPHL-BioNGS/Cecret#147]
There is renewed interest for nanopore sequencing.

If I remember correctly, this just involves the artic workflow creating a consensus fasta file, which can then be used downstream.

I will need some time to look into this, however, and some sample files.

**Comment by danpolanco** [comment]
Hopefully this helps for sample files:

We submit all of our clinical sequencing data for samples that received at least 50% reference genome coverage to NCBI. The human read scrubbed fastq files can be found in the SRA submissions associated with our BioProject PRJNA686984.

Let me know if I can help any other way!

**Comment by erinyoung** [comment]
Forgive me for taking so long to address this. I have a PR that's almost ready to get released (https://github.com/UPHL-BioNGS/Cecret/pull/221) which might address this issue. This will use artic's pipeline for nanopore reads and allow the generated files into the normal subworkflows (i.e. for pangolin or freyja)

Nanopore reads will be able to be read in via a directory
```
nextflow run UPHL-BioNGS/Cecret --nanopore <directory with nanopore reads>
```
Or in a sample sheet
```
sample,fastq_1,fastq_2
example,example.fastq.gz,nanopore
```

And then the sample sheet is read in with the sample_sheet param.
```
nextflow run UPHL-BioNGS/Cecret --sample_sheet samplesheet.csv
```

I'm running several files through now, and I'm going to compare results to see if what I've done makes sense.
