### ISSUE TITLE
mpx_idt profile

### ISSUE THREAD

**Issue by tpillone** [UPHL-BioNGS/Cecret#171]
Hi, 

I'm trying to run Ceret using the Monkeypox IDT profile (mpx_idt), but the the config file _mpx_idt.config_ seems to be missing from the configs folder. Am I missing something? 

Thank you

**Comment by erinyoung** [comment]
You are 100% correct. What an oversight on our part! (We had them locally, but just never committed them. How embarrassing!)

Pull request https://github.com/UPHL-BioNGS/Cecret/pull/172 _should_ resolve this issue.

You can use this branch before it is merged with 

```
nextflow pull UPHL-BioNGS/Cecret
nextflow run UPHL-BioNGS/Cecret -r config <everything else you had in your command line>
```

**Comment by tpillone** [comment]
Thanks a lot for the quick reply!
