### ISSUE TITLE
Combined fasta Issue

### ISSUE THREAD

**Issue by whottel** [UPHL-BioNGS/Cecret#192]
Hello,

I was running cecret on a collection of sequences, and it kept failing on the vadr step. Tracking down the error file in the nextflow work directory:
[Error.txt](https://github.com/UPHL-BioNGS/Cecret/files/11873956/Error.txt)

Checking the concatenated fasta file (coverted to .txt here):
[ultimate_fasta.txt](https://github.com/UPHL-BioNGS/Cecret/files/11873969/ultimate_fasta.txt)

There is a blank row under what seems to be the offending sequence ">Consensus_VA-0266-IA-VH01284-230609__S85.consensus_threshold_0.6_quality_20"
I am not sure why this occurs as on the same run there were other samples with virtually empty fastq files that were excluded from this concatenated fasta file. 

Strangely when I run on a small subset that still includes this sequence, it no longer shows up in the concatenated fasta files and the pipeline runs without error. 
[combined.txt](https://github.com/UPHL-BioNGS/Cecret/files/11873991/combined.txt)

-Wes

**Comment by erinyoung** [comment]
That is strange that it the empty fasta was incorporated into `ultimate_fasta.fasta`. Hmm.... what version of Cecret are you using?

I may need to add an additional check into fasta size.

**Comment by whottel** [comment]
This was run with v.3.7.20230620

**Comment by erinyoung** [comment]
Is it possible to share the fasta file that is causing issues? I'd like to include it in testing.

**Comment by whottel** [comment]
This is the fasta file that is produced by Cecret for that sample.
[VA-0266-IA-VH01284-230609__S85.consensus.fa.txt](https://github.com/UPHL-BioNGS/Cecret/files/11874922/VA-0266-IA-VH01284-230609__S85.consensus.fa.txt)

**Comment by erinyoung** [comment]
Thank you! Hopefully I'll have a fix by COB tomorrow! (it not, it should be _soon_)

**Comment by whottel** [comment]
Awesome, thanks!

**Comment by erinyoung** [comment]
My apologies for taking so long. I think I have an additional fix. 

Once https://github.com/UPHL-BioNGS/Cecret/pull/194 finishes testing, I'll be able to merge this into master and get another update out.

**Comment by whottel** [comment]
Thanks, it looks like the issue is resolved with version 3.7.20230711.
