### ISSUE TITLE
"ch_msa" error with --msa nextclade

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Cecret#197]
When I run Cecret with the following command-line including "--msa nextclade":

nextflow run UPHL-BioNGS/Cecret -profile singularity --medcpus 70 --maxcpus 100 --reads reads --relatedness true --msa nextclade -c configs/cecret.config -resume

I get this error:

Jul-12 17:32:14.951 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: ch_msa for class: nextflow.script.WorkflowBinding
groovy.lang.MissingPropertyException: No such property: ch_msa for class: nextflow.script.WorkflowBinding

**Comment by erinyoung** [comment]
There's an error in the readme!

In your command 'nextclade' should be 'nextalign'

nextflow run UPHL-BioNGS/Cecret -profile singularity --relatedness true --msa nextalign

**Comment by DrB-S** [comment]
I just noticed that! Thanks.

**Comment by erinyoung** [comment]
README.md has been adjusted in https://github.com/UPHL-BioNGS/Cecret/pull/200
