### ISSUE TITLE
Add heatmap for snp-dists output

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Cecret#198]
I have modified my version of HeatCluster.py to work with snp-dists output from Cecret as well as Grandeur.  
[HeatCluster-0.3.4.py.gz](https://github.com/UPHL-BioNGS/Cecret/files/12044666/HeatCluster-0.3.4.py.gz)

**Comment by DrB-S** [comment]
I found a bug in the latest modification I sent yesterday. This new version solves the problem with a list compression.  
[HeatCluster-0.3.6.py.gz](https://github.com/UPHL-BioNGS/Cecret/files/12053817/HeatCluster-0.3.6.py.gz)

**Comment by erinyoung** [comment]
Thanks! 

I'm wondering, though, that since this script is used by more than one workflow, it might be easier to maintain it in a container that gets pulled by both workflows.

**Comment by DrB-S** [comment]
I have tested this latest version, HeatCluster-0.4.0.py, with both Cecret and Grandeur, so that it can be pulled by both workflows. I am also including two test snp matrix files (snp_matrix.txt and snp-dists.txt).  
[HeatCluster-0.4.0.py.gz](https://github.com/UPHL-BioNGS/Cecret/files/12112830/HeatCluster-0.4.0.py.gz)
[snp_matrix.txt](https://github.com/UPHL-BioNGS/Cecret/files/12112831/snp_matrix.txt)
[snp-dists.txt](https://github.com/UPHL-BioNGS/Cecret/files/12112832/snp-dists.txt)

**Comment by DrB-S** [comment]
Changed the name of the latest HeatCluster file to HeatCluster.py so that it can be directly compared with the current version.  Need to learn how to create the test using the snp matrices, rather than testing by running HeatCluster.py manually.
[HeatCluster.py.gz](https://github.com/UPHL-BioNGS/Cecret/files/12112889/HeatCluster.py.gz)

**Comment by erinyoung** [comment]
I'm closing this issue in favor of augmenting https://github.com/DrB-S/HeatCluster
