### ISSUE TITLE
Freyja 1.4.5 depthcutoff

### ISSUE THREAD

**Issue by whottel** [UPHL-BioNGS/Cecret#211]
Hello,

I am using Cecret v.3.7.20230725, which looks to now be using the updated freyja container 1.4.5-20230808.
With this new version for some wastewater SC2 samples I am getting the following freyja demix error:
"demix: Solver error encountered, most likely due to insufficient sequencing depth. Try increasing the --depthcutoff parameter."

These samples do produce a demix file with freyja version 1.4.4-20230718.

It looks like 1.4.5-20230808 added the `--depthcutoff` parameter to  `freyja demix` with defauly value set to 0. 
In a shell session of the freyja image I was able to produce a demix file for the impacted samples by setting `--depthcutoff` to 10 when running `freyja demix`.
Can `--depthcutoff` be set to a value other than 0 in a cecret config file, or can this be value be set to the same value as `params.minimum_depth`?
Also, attached are the depths and variants files of an example impacted sample generated using Cecret v.3.7.20230725. 

[2312877-SC2WW-IA-VH01284-230809_S82_depths.tsv.xlsx](https://github.com/UPHL-BioNGS/Cecret/files/12324418/2312877-SC2WW-IA-VH01284-230809_S82_depths.tsv.xlsx)
[2312877-SC2WW-IA-VH01284-230809_S82_variants.tsv.xlsx](https://github.com/UPHL-BioNGS/Cecret/files/12324420/2312877-SC2WW-IA-VH01284-230809_S82_variants.tsv.xlsx)

Thanks,
Wes

**Comment by erinyoung** [comment]
Yes! You can adjust `params.freyja_demix_options`.

In a config file it looks like
```
params.freyja_demix_options = '--depthcutoff 10'
```

On the command line it would look like
```
<your typical command> --freyja_demix_options '--depthcutoff 10'
```

I'll look into setting the default for freyja demix to align better with the `minimum_depth` parameter.

**Comment by whottel** [comment]
Great, thanks for the quick response!
I will update my config and run again.

-Wes
