### ISSUE TITLE
error while loading shared libraries: libQt5Core.so.5

### ISSUE THREAD

**Issue by ramirobarrantes** [UPHL-BioNGS/Cecret#228]
I upgraded to the latest Cecret 3.8.20230830, and I notice that now it uses samtools 1.18

We encountered an error on one of the samtools step: 

plot-ampliconstats -size 1200,900 -size2 1200,900 -size3 1200,900       samtools_plot_ampliconstats/23-007331-WGS-02-VT-M05220-230912       23-007331-WGS-02-VT-M05220-230912_ampliconstats.txt

and I get: 

Command error:
  gnuplot: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file:
 No such file or directory
  gnuplot:  at /usr/local/bin/plot-ampliconstats line 100.

I've never got that before. I fixed it by using the local samtools and gnuplot and also adjusting the LD_LIBRARY_PATH, although I am not sure if all of those were necessary. Have other people encountered this?

My command was:
nextflow run main.nf -profile singularity,artic_V4 --reads readsDirectory --outdir outputDirectory --relatedness true

**Comment by erinyoung** [comment]
Oh no!

I can't replicate the error on my end, (but singularity can use my home directory which may have the library that it's looking for - so I believe you).

I'm going to put in a quick fix today that will revert the version back to 1.17. Stay tuned!

**Comment by ramirobarrantes** [comment]
I am also happy to see if reverting it back to 1.17 fixes it and get back to you?

From: Young ***@***.***>
Reply-To: UPHL-BioNGS/Cecret ***@***.***>
Date: Friday, September 15, 2023 at 11:43 AM
To: UPHL-BioNGS/Cecret ***@***.***>
Cc: Ramiro ***@***.***>, Author ***@***.***>
Subject: Re: [UPHL-BioNGS/Cecret] error while loading shared libraries: libQt5Core.so.5 (Issue #228)
Resent-From: ***@***.***>
Resent-Date: Friday, September 15, 2023 at 11:43 AM


[ This message was sent from an address outside the Larner College of Medicine. Please exercise caution when clicking links or opening attachments from this source. ]

Oh no!

I can't replicate the error on my end, (but singularity can use my home directory which may have the library that it's looking for - so I believe you).

I'm going to put in a quick fix today that will revert the version back to 1.17. Stay tuned!

**Comment by erinyoung** [comment]
The most recent version (https://github.com/UPHL-BioNGS/Cecret/releases/tag/3.8.20230915) uses version 1.17. Hopefully that resolves your issues. 

This also might be a memory issue. I've tried to replicate the error, and was able to get the same error message if I overloaded my cpus.

**Comment by ramirobarrantes** [comment]
Hi Erin,

Thank you very much.  I have been meaning to write to you today, I did try to shift to 1.17 and that did not solve it. What DID solve it was to comment out the container but rather use my local CONDA environment with two things installed: samtools 1.18 and gnuplot . That fixed the problem for us, I tried it on two different users (myself and a colleague).  Maybe that will provide some hints.

Thanks so much for all your help and for providing this great pipeline! I know it must be a lot of work to maintain,

Ramiro

From: Young ***@***.***>
Reply-To: UPHL-BioNGS/Cecret ***@***.***>
Date: Tuesday, September 19, 2023 at 4:41 PM
To: UPHL-BioNGS/Cecret ***@***.***>
Cc: Ramiro ***@***.***>, Author ***@***.***>
Subject: Re: [UPHL-BioNGS/Cecret] error while loading shared libraries: libQt5Core.so.5 (Issue #228)
Resent-From: ***@***.***>
Resent-Date: Tuesday, September 19, 2023 at 4:41 PM


[ This message was sent from an address outside the Larner College of Medicine. Please exercise caution when clicking links or opening attachments from this source. ]

The most recent version (https://github.com/UPHL-BioNGS/Cecret/releases/tag/3.8.20230915) uses version 1.17. Hopefully that resolves your issues.

This also might be a memory issue. I've tried to replicate the error, and was able to get the same error message if I overloaded my cpus.
