### ISSUE TITLE
Add heatcluster

### ISSUE THREAD

**Issue by erinyoung** [UPHL-BioNGS/Cecret#244]
Heatcluster is a useful tool for visualizing SNP matrices. 

https://github.com/DrB-S/HeatCluster

To add Heatcluster 
[ ] HeatCluster needs to be put in a container
[ ] There needs to be a new process for running HeatCluster (needs the HeatCluster container)
[ ] The results from SNP-dists need to be put into a channel
[ ] That channel needs to put the SNP-dists output to the Heatcluster process
[ ] The output of the HeatCluster process needs to be put into a channel
[ ] The results from HeatCluster need to go to the MultiQC process

**Comment by erinyoung** [comment]
https://github.com/UPHL-BioNGS/Cecret/pull/241 is a related PR.

**Comment by erinyoung** [comment]
Closed by https://github.com/UPHL-BioNGS/Cecret/pull/254

**Comment by DrB-S** [comment]
I have updated the Dockerfile for heatcluster:0.4.12, and have deposited the latest docker image on ghcr.io.  See:

$ docker images |grep heatcluster
heatcluster                                 0.4.12                     8e2924956336   13 minutes ago   470MB
ghcr.io/drb-s/heatcluster          0.4.12                     8e2924956336   13 minutes ago   470MB

Does this give you the information you need to grab the docker image?

**Comment by DrB-S** [comment]
[Dockerfile.txt](https://github.com/UPHL-BioNGS/Cecret/files/13398160/Dockerfile.txt)

FROM ubuntu:jammy as app
ARG HEATCLUSTER_VER="0.4.12"

LABEL base.image="ubuntu:jammy"
LABEL dockerfile.version="1"
LABEL software="HeatCluster"
LABEL software.version="${HEATCLUSTER_VER}"
LABEL version="${HEATCLUSTER_VER}"
LABEL description="Visualize SNP matrix from snp-dists output"
LABEL website="https://github.com/DrB-S/heatcluster"
LABEL license="https://github.com/DrB-S/heatcluster/blob/master/LICENSE"
LABEL name="heatcluster/${HEATCLUSTER_VER}"
LABEL maintainer="Stephen Beckstrom-Sternberg"
LABEL maintainer.email="stephen.beckstrom-sternberg@azdhs.gov"

RUN echo "Installing python and pip" && echo
RUN apt-get update && apt-get install -y --no-install-recommends \
ca-certificates \
  wget \
  procps \
  python3 \
  python3-pip && \
  apt-get autoclean && rm -rf /var/lib/apt/lists/*

RUN echo "Installing python packages" && echo
RUN pip3 install --no-cache argparse pandas numpy pathlib seaborn matplotlib scipy --upgrade-strategy=only-if-needed

RUN pwd && ls -la

RUN echo "Installing heatcluster from archive: " && echo
RUN wget -q https://github.com/DrB-S/heatcluster/archive/refs/tags/v${HEATCLUSTER_VER}.tar.gz && \
  tar -vxf v${HEATCLUSTER_VER}.tar.gz && \
  pwd && ls -latr && \
  rm v${HEATCLUSTER_VER}.tar.gz && \
  cd heatcluster-${HEATCLUSTER_VER} && ls -la 


ENV PATH="/heatcluster-${HEATCLUSTER_VER}:$PATH" \
LC_ALL=C


RUN pwd; ls -la
WORKDIR /heatcluster-${HEATCLUSTER_VER}

FROM app as test

RUN echo && echo "Show heatcluster version number and help file:  " && echo 
RUN heatcluster.py --version && echo && \
heatcluster.py --help

RUN echo && echo "Test a small and medium matrix :" && echo && echo && \
heatcluster.py -i test/small_matrix.csv -t png -o small && \
heatcluster.py -i test/med_matrix.txt -t png -o med

RUN echo && ls -lh|tail && echo "DONE"

WORKDIR /heatcluster-${HEATCLUSTER_VER}
CMD [ "/bin/ls", "-l" ]
