### ISSUE TITLE
Test run ...

### ISSUE THREAD

**Issue by vangalamaheshh** [UPHL-BioNGS/Cecret#28]
Hello @erinyoung -

I installed singularity, nextflow on my mac.
I git cloned this repo and have a test fastq file (single end).
I was hoping I can run the command,

nextflow Cecret/Cecret.nf 

But, it fails with fastqc command not found.
I was assuming the script might pull necessary containers and thus no need to install dependencies on my laptop before running this script.
I see containers.config in configs directory.
If I want to run this script using singularity, how should I invoke the command or configure this software?
Thank you in advance.

Best,
Mahesh

**Comment by vangalamaheshh** [comment]
Hello again,

Never mind, I tried with -c flag giving configs/singularity.confg as argument, and things seem to be peachy.

Thank you,
Mahesh

**Comment by erinyoung** [comment]
@vangalamaheshh You can also customize the config to suite your individual analysis needs. 

If you don't want to use singularity, you'll want each tool to be in your path and adjust the files appropriately.
