### ISSUE TITLE
Segmentation fault for iVar variants process

### ISSUE THREAD

**Issue by k-florek** [UPHL-BioNGS/Cecret#31]
When running iVar occasionally throws a segmentation fault possibly related to samtools usage of memory. 

```
Command exit status:
  139
Command output:
  (empty)
Command error:
  .command.sh: line 11:    37 Broken pipe             samtools mpileup -A -d 8000 -B -Q 0 --reference MN908947.3.fasta 091176-44249.primertrim.sorted.bam 2>> $err_file
          38 Segmentation fault      (core dumped) | ivar variants -p ivar_variants/091176-44249.variants -q 20 -t 0.6 -m 10 -r MN908947.3.fasta -g MN908947.3.gff 2>> $err_file >> $log_file
```

Giving the process addition memory after a retry seems to fix the issue:
```
memory {2.GB * task.attempt}
errorStrategy {'retry'}
maxRetries 2
```

I'm opening a pull request to add this to the process in case you want to include the changes to the workflow.

**Comment by erinyoung** [comment]
Thank you for this! I added your suggestion to the following processes : 
* ivar_variants
* ivar_consensus
