### ISSUE TITLE
Setting a minimum variant cutoff for Freyja

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Cecret#311]
Is there a way to set a minimum variant cutoff to 1%? I take it that means setting the abundance to 0.01 in Freyja. Would that be using the Freyja eps option (--eps 0.01)? And if so, is there a config I can edit to set that, or can it be set on the command-line when running Cecret?

**Comment by erinyoung** [comment]
For Freyja demix? Yes, there are currently two ways to do this:
1. using the `freyja_demix_options` parameter
   A. On the command line:
   `--freyja_demix_options "--eps 0.01"`, but this has a "--" which may cause issues with some versions of nextflow)
   B. In a config file:
   ```
   params.freyja_demix_options = "--eps 0.01"
   ```
 2. Setting the task.ext.arg in a "process" scope in a config file
 ```
 process {
     withName:freyja_demix {
         ext.args = "--eps 0.01"
     }
 }
 ```
 
When I tested these parameters, this generally causes the workflow to take longer and reduces the number of lineages that freyja identifies.

**Comment by DrB-S** [comment]
Thanks!
