### ISSUE TITLE
Uncommitted changes prevent updating Cecret

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Cecret#328]
nextflow pull UPHL-BioNGS/Cecret
Checking UPHL-BioNGS/Cecret ...
UPHL-BioNGS/Cecret contains uncommitted changes -- cannot pull from repository

Is there something I need to change at my end?

**Comment by erinyoung** [comment]
This is probably something with nextflow. You'll need to delete your local version and re-pull it.

Something like
```
rm -rf ~/.nextflow/*/UPHL-BioNGS/Cecret
nextflow pull UPHL-BioNGS/Cecret
```

**Comment by DrB-S** [comment]
Thanks! It is working now!
