### ISSUE TITLE
Adding MT903345 as mpx reference genome

### ISSUE THREAD

**Issue by jl32587** [UPHL-BioNGS/Cecret#342]
Our lab has been using MT903345.1 as reference genome (https://www.medrxiv.org/content/10.1101/2022.10.14.22280783v1.full) using older version of Cecret (v.3.4.20221121). The mpx_primalseq config now uses NC_063383.1. Is it necessary to set up a new profile using  MT903345.1?

**Comment by erinyoung** [comment]
The bedfile coordinates have to match the reference sequence otherwise `ivar trim` or `samtools ampliconclip` can't figure out where the primers are.

Do you have a copy of the bedfile that you could share with me?

**Comment by jl32587** [comment]
[TX-DSHS_Mpx_bed.zip](https://github.com/user-attachments/files/15980326/TX-DSHS_Mpx_bed.zip)
I have attached the reference fasta and bed files we are using. Thank you!

**Comment by erinyoung** [comment]
I DID NOT forget about this. 

It's just that testing this takes a really long time.

I have added in new primer schemes that I have labeled mpx_yale into the [latest updates that are currently going through testing](https://github.com/UPHL-BioNGS/Cecret/pull/347).

If all goes well, this should get released by the end of the day. /fingerscrossed

To use these primers, you would set the `params.primer_set = "mpx_yale"` and `params.species = "mpx"` OR add mpx_yale to your profiles.

What command do you normally use? I can convert that to use these new values.

**Comment by jl32587** [comment]
Thank you so much for working on this! The command I normally used is:
nextflow run UPHL-BioNGS/Cecret --reads <input_path> --outdir <output_path> -profile singularity,mpx_primalseq

**Comment by erinyoung** [comment]
The new release is out!!!

I've named the profile that uses these primers the 'mpx_yale' profile. You _should_ be able to run what you normally ran by updating the profile from mpx_primalseq to mpx_yale.

```
nextflow run UPHL-BioNGS/Cecret --reads <input_path> --outdir <output_path> -profile singularity,mpx_yale
```

**Comment by jl32587** [comment]
Sweet! I'll test it on our dataset. Appreciate it!
