### ISSUE TITLE
Extra lines in summary file with large number of samples

### ISSUE THREAD

**Issue by garfinjm** [UPHL-BioNGS/Cecret#344]
Hello again!

I'm encountering an issue where extra lines are added to the `cecret_results.csv` file when a large number (hundreds) of samples are run together.

Basically, I get two extra lines in my `cecret_results.csv` that look like:

> name,name,,,p/f,,,,,,,,model,alerts,,,,,,,,,,,,,,,,,,,,,,v3.14.240610,artic 1.2.4
> seq,seq,,,best,,,,,,,,seq,,,,,,,,,,,,,,,,,,,,,,,v3.14.240610,artic 1.2.4

This only seems to happen when I run large batches of samples through together. I've tracked these extra lines back to  the `vadr.sqa` file used during the cecret summary process (see: https://github.com/ncbi/vadr/issues/81)

I think one possible fix would be to edit the line below replacing `grep -v "#-"` with `grep -v "^#"`" (as Eric suggests in the vadr issue).

https://github.com/UPHL-BioNGS/Cecret/blob/afe58161be62c956e1999f1a655764b60035ac09/modules/cecret.nf#L122

Let me know if you need any other info or want me to try something else on my setup, and thanks again for all your work on Cecret.

**Comment by erinyoung** [comment]
Oh SNAP!

**Comment by erinyoung** [comment]
FYI, I'm working on this today

**Comment by erinyoung** [comment]
I actually need the vadr header, but the [latest set of updates](https://github.com/UPHL-BioNGS/Cecret/pull/347) that are currently going through testing should fix the issue you are seeing.

Thank you for bringing this to my attention!

**Comment by erinyoung** [comment]
This issue should be fixed now!!!

**Comment by garfinjm** [comment]
Works perfect, thanks for the update!
