### ISSUE TITLE
Process `summary` input file name collision

### ISSUE THREAD

**Issue by fanninpm** [UPHL-BioNGS/Cecret#37]
When both `params.pangolin` and `params.vadr` are set to `false`, nextflow complains:

```none
Error executing process > 'summary (P120-S09-00846-4-S_S24)'

Caused by:
  Process `summary` input file name collision -- There are multiple input files for each of the following file names: Cecret.nf

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

Possible offending lines:

https://github.com/UPHL-BioNGS/Cecret/blob/c683a197604ebd2f703ceb1cb8f187e8d2a2e0db/Cecret.nf#L1134-L1136

https://github.com/UPHL-BioNGS/Cecret/blob/c683a197604ebd2f703ceb1cb8f187e8d2a2e0db/Cecret.nf#L1233-L1235

This was run with version 1.3.3 of the StaPH-B toolkit, which may not include an up-to-date workflow file.

**Comment by erinyoung** [comment]
That was a hacky way to accomplish this anyway. 

The new version should not have this issue.

**Comment by erinyoung** [comment]
The StaphB toolkit should be updated _soon_ish

**Comment by erinyoung** [comment]
It should be fixed in the staph-b toolkit now. 
https://github.com/StaPH-B/staphb_toolkit/pull/59
