### ISSUE TITLE
Samplesheet for nanopore reads not working

### ISSUE THREAD

**Issue by hutchinsonmiri** [UPHL-BioNGS/Cecret#375]
Hi! I am attempting to use a samplesheet for some nanopore reads but Cecret seems to interpreting the reads as paired-end. I am able to run the pipeline just fine when the fastqs are in a directory. My sample sheet is formatted as follows:
sample,fastq_1,fastq_2
2024028971,/Projects/Research/Cecret/Cecret_v3.12.20240227_nano/nanopore/2024028971.fastq.gz,nanopore
2024028978,/Projects/Research/Cecret/Cecret_v3.12.20240227_nano/nanopore/2024028978.fastq.gz,nanopore
2024028980,/Projects/Research/Cecret/Cecret_v3.12.20240227_nano/nanopore/2024028980.fastq.gz,nanopore

The pipeline reports that paired-end reads were found:
Paired-end Fastq files found : 2024028971
Paired-end Fastq files found : 2024028978
Paired-end Fastq files found : 2024028980

And then fails at the fastqc step.

Do you have any advice? Thanks so much in advance!!

**Comment by erinyoung** [comment]
!!!

It looks like the documentation doesn't match what the sample sheet is actually supposed to contain. (meaning, this is my issue, not yours)


What happens if you use ont for column 3 (the fastq_2 column) instead of nanopore?
```
sample,fastq_1,fastq_2
2024028971,/Projects/Research/Cecret/Cecret_v3.12.20240227_nano/nanopore/2024028971.fastq.gz,ont
2024028978,/Projects/Research/Cecret/Cecret_v3.12.20240227_nano/nanopore/2024028978.fastq.gz,ont
2024028980,/Projects/Research/Cecret/Cecret_v3.12.20240227_nano/nanopore/2024028980.fastq.gz,ont
```

**Comment by hutchinsonmiri** [comment]
Thanks! Strangely when I try that, it seems to be interpreting 'ont' as the name of one of the reads as artic begins to proceed (according to the command error):

usage: artic [-h] [-v]
             {extract,basecaller,demultiplex,minion,gather,guppyplex,filter,rampart,export,run}
             ...
artic: error: unrecognized arguments: ont]


Also, I am getting this error (repeated for each of the samples):
[4f/64a662] NOTE: Missing output file(s) `artic/2024028971_filtered.fastq.gz` expected by process `CECRET:cecret:artic_read_filtering (2024028971)` -- Execution is retried (1)


Thanks again for your help!!

**Comment by erinyoung** [comment]
I'm going to have to look into this. My kiddo is home because of a school break, but I'm confident I can fix this by tomorrow.

**Comment by hutchinsonmiri** [comment]
Thanks a bunch!!! I really appreciate it.

**Comment by erinyoung** [comment]
I've created a PR that should fix the issue: https://github.com/UPHL-BioNGS/Cecret/pull/378

Basically, the nanopore file was read in with an extra string which was causing the error. 

This PR is currently undergoing testing, but once testing is finished, version 3.15.24296 will be released and shouldn't have that extra string that is throwing the error.

**Comment by erinyoung** [comment]
It should be fixed now. Let me know if you run into issues!

**Comment by hutchinsonmiri** [comment]
Thanks!!!! Appreciate your assistance!!
