### ISSUE TITLE
Error executing process > 'fastqc (12)'

### ISSUE THREAD

**Issue by mramirezs** [UPHL-BioNGS/Cecret#60]
I don't know what is the problem. I reinstalled fastqc from the link, but I can't fix. Please.

Furthermore, I left the complete output:

 Error executing process > 'fastqc (12)'

Caused by:
  Process `fastqc (12)` terminated with an error exit status (1)

Command executed:

  mkdir -p fastqc logs/fastqc
  log_file=logs/fastqc/12.427d29a5-7e5f-482e-82cd-7be02fedbeea.log
  err_file=logs/fastqc/12.427d29a5-7e5f-482e-82cd-7be02fedbeea.err

time stamp + capturing tool versions
  date | tee -a $log_file $err_file > /dev/null
  fastqc --version >> $log_file

  fastqc        --outdir fastqc       --threads 1       12_S12_L001_R1_001.fastq.gz 12_S12_L001_R2_001.fastq.gz       2>> $err_file >> $log_file

  zipped_fastq=($(ls fastqc/*fastqc.zip) "")

  raw_1=$(unzip -p ${zipped_fastq[0]} */fastqc_data.txt | grep "Total Sequences" | awk '{ print $3 }' )
  raw_2=NA
  if [ -f "${zipped_fastq[1]}" ] ; then raw_2=$(unzip -p fastqc/*fastqc.zip */fastqc_data.txt | grep "Total Sequences" | awk '{ print $3 }' ) ; fi

  if [ -z "$raw_1" ] ; then raw_1="0" ; fi
  if [ -z "$raw_2" ] ; then raw_2="0" ; fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: failed to set O_CLOEXEC flags on image
  WARNING: failed to set O_CLOEXEC flags on image
  ERROR  : Failed to set securebits: Invalid argument
  ERROR  : Failed to set securebits: Invalid argument

**Comment by erinyoung** [comment]
I have not encountered this error before, but I googled your error and it appears to happen when using singularity with windows.

Are you using windows?

You might want to use docker instead of singularity. That can be done by using a different config file. I'm hoping that fixes your issue.
```
nextflow run Cecret.nf -c configs/docker.config
```

🤞

**Comment by mramirezs** [comment]
Hi 

When I worked with docker, I had the same problem.

**Comment by erinyoung** [comment]
What error did it give you when using docker?

Do any singularity containers work in your environment?

This workflow isn't designed to use the fastqc that is installed on your computer. It is going to pull a container (either via docker or singularity, although it's looking like singularity does not play well with windows), and then use that container to execute the process. Admittedly, if there's something wrong with pulling and using the containers, there's not much that I can do.

If you don't want to use any containers, every executable for each process will need to be in your path, and you'll need to be a bash-friendly environment. 

This options would be run with:

```
nextflow run Cecret.nf
```

There are quite a few processes in this workflow, however, and I will not be able to support this option.

**Comment by erinyoung** [comment]
I hope all is well with you. Cecret has gone through an update that may help with your problem. It's now has profiles instead of forcing the end user to put the path into a config file.

**Comment by erinyoung** [comment]
https://github.com/UPHL-BioNGS/Cecret/pull/65
