### ISSUE TITLE
Adjust defaults to artic V4 primers

### ISSUE THREAD

**Issue by erinyoung** [UPHL-BioNGS/Cecret#67]
This is in the works, but probably won't get worked on until someone requests this feature.

**Comment by kittychaseNC** [comment]
I'll request it :)  We are hoping to start running the 4.1 set this week and I'd like to use Cecret.

**Comment by erinyoung** [comment]
That's awesome!

I've added the artic v4 and v4.1 spike in files and changed some defaults.

It's currently on the erin-dev branch of this repo. I'm running my tests tonight, and should update the master branch once the tests are done.

**Comment by erinyoung** [comment]
@kittychaseNC ,

The latest and great version of 'Cecret' is now ready for use. I think you're going to want a version past '2.3.20220114'

The default primer scheme of the 'Cecret' workflow is the 'V4' primer scheme developed by artic network for SARS-CoV-2. Releases prior to and including '2.2.20211221' used the 'V3' primer scheme as the default. As many public health laboratories are still using 'V3', the 'V3' files are still in this repo, but now the 'V4' and 'V4.1' ('V4' with a spike-in of additional primers) are also included. The original primer and amplicon bedfiles can be found at artic's github repo. The recommended method to use these primer sets is with the corresponding profile.

```
# using artic V3 primers
nextflow run UPHL-BioNGS/Cecret -profile singularity,artic_V3

# using artic V4 primers
nextflow run UPHL-BioNGS/Cecret -profile singularity,artic_V4

# using artic V4.1 primers
nextflow run UPHL-BioNGS/Cecret -profile singularity,artic_V4_1
```
It is still possible to set 'params.primer_bed' and 'params.amplicon_bed' via the command line or in a config file with the path to the corresponding file.

Let me know if you run into any issues!

**Comment by kittychaseNC** [comment]
Thanks Erin!!
