### ISSUE TITLE
what if I want the input as assembled fastas?

### ISSUE THREAD

**Issue by Shaokang123** [UPHL-BioNGS/Cecret#75]
Hi,
Impressive binf tool! May I ask what shall I do if I just want the input to be the assembled fastas to get the analysis such as phylogeny, pangolin, vadr,  etc.?
Regards,
Shaokang

**Comment by erinyoung** [comment]
Right now Cecret expects individual fastas. You can split your multifastas into individual fastas through something like
```
awk '/^>/{s=++d".fa"} {print > s}' multi.fasta
```

I thought about putting in multifasta support, but didn't find anyone interested. 

Until NOW!

Omicron willing, I might be able to have input functionality for this by the end of the week.

**Comment by Shaokang123** [comment]
Thanks Young, may I ask what to do if I want the input as assembled fastas only, without providing fastqs, etc.. Let me know if it is possible.
Regards,
Shaokang

**Comment by erinyoung** [comment]
Put your fastas into a directory. Then specify which directory with `params.fastas = "directory of your fastas"` or use `--fastas "directory of your fastas"` on the command line.

The default is the a directory named 'fastas' in the directory where you launch the script.

**Comment by erinyoung** [comment]
Did you get everything working?

If `params.fastas = '<directory of your fastas>'` isn't working, there's now a `params.multifastas = 'directory of your fastas'` that might be worth trying.

https://github.com/UPHL-BioNGS/Cecret/releases/tag/2.2.20211209

**Comment by Shaokang123** [comment]
Hey Young,
Thanks. I put target fastas to "fastas" directory. But got below error:

```
ERROR ~ No such variable: sample

 -- Check script 'Cecret.nf' at line: 158 or see '.nextflow.log' file for more de tails
```

Regards,
Shaokang

**Comment by erinyoung** [comment]
That's a bit of a problem. 

What version of the workflow are you using? The current one is `v.2.2.20211210`.

I just reran my tests, and they're working, so there must be something I'm not testing for.

Is there a way you could share your command with me and your files?

**Comment by Shaokang123** [comment]
Hey Young, 

Thanks. The version I used is v.2.1.20211120 
I just put fastas into the dir, then run below, let me know if this is the correct way to use
`nextflow run Cecret.nf -c configs/docker.config`

Regards,
Shaokang

**Comment by erinyoung** [comment]
Your repo is a little out of date, but, yes, that's the general usage.

```
nextflow run <directory with Cecret's github repo>/Cecret.nf -c <directory with Cecret's github repo>/configs/docker.config --fastas <directory where your fastas are> --outdir <directory where you want your results>
```

**Comment by Shaokang123** [comment]
Wonderful! Thanks Young!
Shaokang
