### ISSUE TITLE
Error executing process > 'pangolin (SARS-CoV-2 lineage Determination)'

### ISSUE THREAD

**Issue by SVN-PhD** [UPHL-BioNGS/Cecret#83]
This was using the git cloned version of Cecret. Error from NextFlow:

> Error executing process > 'pangolin (SARS-CoV-2 lineage Determination)'
> 
> Caused by:
>   Process `pangolin (SARS-CoV-2 lineage Determination)` terminated with an error exit status (2)
> 
> Command executed:
> 
>   mkdir -p pangolin logs/pangolin
>   log_file=logs/pangolin/pangolin.11a368d3-9f2d-4abc-b735-f07ad370a00d.log
>   err_file=logs/pangolin/pangolin.11a368d3-9f2d-4abc-b735-f07ad370a00d.err
>   
>   date | tee -a $log_file $err_file > /dev/null
>   pangolin --all-versions >> $log_file
>   
>   for fasta in 2111180087.consensus.fa
>   do
>     cat $fasta >> ultimate_fasta.fasta
>   done
>   
>   pangolin        --threads 4       --outdir pangolin       ultimate_fasta.fasta       2>> $err_file >> $log_file
>   cp ultimate_fasta.fasta pangolin/combined.fasta
> 
> Command exit status:
>   2
> 
> Command output:
>   (empty)
> 
> Command error:
>   WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
>   usage: pangolin <query> [options]
>   pangolin: error: unrecognized arguments: --all-versions
> 
> Work dir:
>   /home/mdubfx/cecret_test/Cecret/work/be/1e5b21170bcb2897537dc02b9f6f8b
> 
> Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

The StaPH-B version of Cecret is also crashing at the pangolin stage. Thanks!

**Comment by erinyoung** [comment]
This is an alarming issue. I would like to get this resolved fairly soon.

```
pangolin: error: unrecognized arguments: --all-versions
```

What pangolin container are you using?

Admittedly I let the StaPH-B version get a little out of date while I was working on bugs (that should be remedied as soon as I clear up all these issues), so would it be possible to share the error message that you observed with the staph-B toolkit?

**Comment by SVN-PhD** [comment]
> Error executing process > 'summary (2111180087)'
> 
> Caused by:
>   Process `summary (2111180087)` terminated with an error exit status (125)
> 
> Command executed:
> 
>   mkdir -p summary logs/summary
>   log_file=logs/summary/2111180087.70a5d324-4c24-4041-8790-69875d9dc92e.log
>   err_file=logs/summary/2111180087.70a5d324-4c24-4041-8790-69875d9dc92e.err
>   
>   date | tee -a $log_file $err_file > /dev/null
>   
>   sample_id=($(echo 2111180087 | cut -f 1 -d "_" ))
>   
>   header="sample_id,sample"
>   result="${sample_id},2111180087"
>   
>   header="$header,pangolin_lineage,pangolin_status,pangolin_scorpio_call"
>   result="$result,AY.25,passed_qc,Delta (B.1.617.2-like)"
>   
>   header="$header,nextclade_clade"
>   result="$result,21J (Delta)"
>   
>   header="$header,fastqc_raw_reads_1,fastqc_raw_reads_2"
>   result="$result,327849,327849"
>   
>   header="$header,seqyclean_pairs_kept_after_cleaning,seqyclean_percent_kept_after_cleaning"
>   result="$result,293714,89.5882"
>   
>   header="$header,fastp_reads_passed"
>   result="$result,null"
>   
>   header="$header,depth_after_trimming,1X_coverage_after_trimming"
>   result="$result,2123.65,99.8161"
>   
>   header="$header,num_pos_100X"
>   result="$result,28275"
>   
>   header="$header,insert_size_before_trimming,insert_size_after_trimming"
>   result="$result,137.2,137.6"
>   
>   organism=$(echo "Severe acute respiratory syndrome-related coronavirus" | sed 's/ /_/g')
>   header="$header,%_human_reads,percent_${organism}_reads"
>   result="$result,null,null"
>   
>   header="$header,ivar_num_variants_identified,bcftools_variants_identified"
>   result="$result,40,null"
>   
>   header="$header,bedtools_num_failed_amplicons,samtools_num_failed_amplicons"
>   result="$result,0,0"
>   
>   header="$header,vadr_conclusion"
>   result="$result,null"
>   
>   header="$header,num_N,num_degenerage,num_non-ambiguous,num_total"
>   result="$result,1574,0,28276,29850"
>   
>   header="$header,pangolin_version,pangolearn_version,constellations_version,scorpio_version"
>   result="$result,3.1.17,2021-11-25,v0.0.28,0.3.15"
>   
>   header="$header,nextclade_version"
>   result="$result,1.4.5"
>   
>   header="$header,cleaner_version,aligner_version,trimmer_version,ivar_version"
>   result="$result,seqyclean : Version: 1.10.09 (2018-10-16),bwa : Version: 0.7.17-r1188,ivar : iVar version 1.3.1 Please raise issues and bug reports at https://github.com/andersen-lab/ivar/,iVar version 1.3.1"
>   
>   echo $header > summary/2111180087.summary.csv
>   echo $result >> summary/2111180087.summary.csv
>   
>   cat summary/2111180087.summary.csv | tr ',' '	' > summary/2111180087.summary.txt
> 
> Command exit status:
>   125
> 
> Command output:
>   (empty)
> 
> Command error:
>   docker: invalid reference format.
>   See 'docker run --help'.
> 
> Work dir:
>   /home/mdubfx/cecret_test/Cecret/211203_cecret2/logs/work/54/812388bc2f8231dd324171747b4f3f
> 
> Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

![Screenshot from 2021-12-13 12-18-26](https://user-images.githubusercontent.com/15314705/145859027-1b57675c-0d0a-41b3-9e84-772babf2a2ec.png)

**Comment by SVN-PhD** [comment]
> Error executing process > 'summary (2111180087)'
> 
> Caused by:
>   Process `summary (2111180087)` terminated with an error exit status (125)
> 
> Command executed:
> 
>   mkdir -p summary logs/summary
>   log_file=logs/summary/2111180087.70a5d324-4c24-4041-8790-69875d9dc92e.log
>   err_file=logs/summary/2111180087.70a5d324-4c24-4041-8790-69875d9dc92e.err
>   
>   date | tee -a $log_file $err_file > /dev/null
>   
>   sample_id=($(echo 2111180087 | cut -f 1 -d "_" ))
>   
>   header="sample_id,sample"
>   result="${sample_id},2111180087"
>   
>   header="$header,pangolin_lineage,pangolin_status,pangolin_scorpio_call"
>   result="$result,AY.25,passed_qc,Delta (B.1.617.2-like)"
>   
>   header="$header,nextclade_clade"
>   result="$result,21J (Delta)"
>   
>   header="$header,fastqc_raw_reads_1,fastqc_raw_reads_2"
>   result="$result,327849,327849"
>   
>   header="$header,seqyclean_pairs_kept_after_cleaning,seqyclean_percent_kept_after_cleaning"
>   result="$result,293714,89.5882"
>   
>   header="$header,fastp_reads_passed"
>   result="$result,null"
>   
>   header="$header,depth_after_trimming,1X_coverage_after_trimming"
>   result="$result,2123.65,99.8161"
>   
>   header="$header,num_pos_100X"
>   result="$result,28275"
>   
>   header="$header,insert_size_before_trimming,insert_size_after_trimming"
>   result="$result,137.2,137.6"
>   
>   organism=$(echo "Severe acute respiratory syndrome-related coronavirus" | sed 's/ /_/g')
>   header="$header,%_human_reads,percent_${organism}_reads"
>   result="$result,null,null"
>   
>   header="$header,ivar_num_variants_identified,bcftools_variants_identified"
>   result="$result,40,null"
>   
>   header="$header,bedtools_num_failed_amplicons,samtools_num_failed_amplicons"
>   result="$result,0,0"
>   
>   header="$header,vadr_conclusion"
>   result="$result,null"
>   
>   header="$header,num_N,num_degenerage,num_non-ambiguous,num_total"
>   result="$result,1574,0,28276,29850"
>   
>   header="$header,pangolin_version,pangolearn_version,constellations_version,scorpio_version"
>   result="$result,3.1.17,2021-11-25,v0.0.28,0.3.15"
>   
>   header="$header,nextclade_version"
>   result="$result,1.4.5"
>   
>   header="$header,cleaner_version,aligner_version,trimmer_version,ivar_version"
>   result="$result,seqyclean : Version: 1.10.09 (2018-10-16),bwa : Version: 0.7.17-r1188,ivar : iVar version 1.3.1 Please raise issues and bug reports at https://github.com/andersen-lab/ivar/,iVar version 1.3.1"
>   
>   echo $header > summary/2111180087.summary.csv
>   echo $result >> summary/2111180087.summary.csv
>   
>   cat summary/2111180087.summary.csv | tr ',' '	' > summary/2111180087.summary.txt
> 
> Command exit status:
>   125
> 
> Command output:
>   (empty)
> 
> Command error:
>   docker: invalid reference format.
>   See 'docker run --help'.
> 
> Work dir:
>   /home/mdubfx/cecret_test/Cecret/211203_cecret2/logs/work/54/812388bc2f8231dd324171747b4f3f
> 
> Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

![Screenshot from 2021-12-13 12-18-26](https://user-images.githubusercontent.com/15314705/145859027-1b57675c-0d0a-41b3-9e84-772babf2a2ec.png)

**Comment by erinyoung** [comment]
It looks like for the StaPH-B toolkit that pangolin is working fine, it's the `process summary` that has run into issues. You have given the error
```
docker: invalid reference format.
```
which is one I'm not familiar with. I'm going to google this for a sec and get back with you.

**Comment by erinyoung** [comment]
I WAS ABLE TO REPLICATE YOUR DOCKER ERROR!!! 🥳 

I normally use singularity, so I was worried.

This must be an issue with the container that's being used. Perhaps there's a typo somewhere. I wonder why it works fine with singularity?

**Comment by SVN-PhD** [comment]
That's great! I was able to get Pangolin to work by `docker pull` the latest versions of Pangolin. The other docker error still persists.

**Comment by erinyoung** [comment]
It's because I put `docker://` at the beginning of the image name. I think. At least, I got the error to go away on my end.

I've created a new release and will push an update to the staphb toolkit by the end of the day, but you could try updating this repo and trying again.

https://github.com/UPHL-BioNGS/Cecret/releases/tag/2.2.20211213

**Comment by SVN-PhD** [comment]
Repo updated and it's working properly, thanks!!
