### ISSUE TITLE
Parsing of Freyja results into cecret results output

### ISSUE THREAD

**Issue by poojasgupta** [UPHL-BioNGS/Cecret#98]
Thank you for adding Freyja in Cecret. It has been very helpful. 
However, freyja results are not getting parsed correctly in the cecret result output. An additional row is being created in the table to output the freyja result. I have attached an example result file for your reference. 

[example_cecret_results.csv](https://github.com/UPHL-BioNGS/Cecret/files/8732174/example_cecret_results.csv)

**Comment by erinyoung** [comment]
I have been able to replicate this, and I think I have a solution. 

Right now it's in the 'edits' branch, and I hope to have the changes pushed to master _soon_
