### ISSUE TITLE
creation of a parameter schema

### ISSUE THREAD

**Issue by k-florek** [UPHL-BioNGS/Cecret#99]
All nf-core workflows include a json parameter schema file in the top level directory that outlines all of the parameters of the workflow. Here are some examples:
[viralrecon](https://github.com/nf-core/viralrecon/blob/master/nextflow_schema.json)  
[mycosnp](https://github.com/CDCgov/mycosnp-nf/blob/master/nextflow_schema.json)  
[bactopia](https://github.com/bactopia/bactopia/blob/master/nextflow_schema.json)

nf-core includes a tool to help with creating the file if you are using nf-core [schema builder](https://nf-co.re/pipeline_schema_builder).

StaPH-B Toolkit v2 will use this file to tell users which parameters can be supplied with each workflow. If there isn't a schema file the toolkit will just inform the user that help is not available for this workflow. Including this file for Cecret will be really helpful for users once I release v2 of the toolkit.

**Comment by erinyoung** [comment]
I won't be able be able to move Cecret v.3.0.20220520 to the staphB toolkit with the current layout of the staphB toolkit.

I'm currently satisfied in defining all the params in the nextflow workflow scripts and a config file for a couple of reasons, one of which is time constraints.

I'm looking forward to the next version of the staphB toolkit.

**Comment by erinyoung** [comment]
This has, in theory, been added with https://github.com/UPHL-BioNGS/Cecret/pull/111.

Let me know if it's not up to snuff.
